### ISSUE TITLE
File in gem is causing security scanner issues

### ISSUE THREAD

**Issue by matobinder** [flavorjones/mini_portile#108]
So we have a application that gets built, that includes mini_portile, and it runs through a security scanner before being deployed.

The scanner gets upset by this file:

/test/assets/test-download-archive.tar.gz

As, it it looks like a tar.gz file, but is really just plain text file
Does this file really need to get delivered with the gem?

For now, after I bundle install it I am just going to delete the file from my vendored dir

**Comment by flavorjones** [comment]
Hi, @matobinder. Thanks for opening this issue, and sorry you're having this problem.

It's a common convention to include tests in a rubygem package, and occasionally I've had conversations with downstream packagers (e.g., Debian package managers) about how they have commonly-used scripts that rely on tests being present (to validate the final package). But we could probably remove the tests if we judge that the inconvenience by packagers is outweighed by solving this problem.

Can you help me understand why you're having this problem? How is your application using mini_portile? Is it getting pulled in via a dependency from another gem (like nokogiri)?

**Comment by matobinder** [comment]
Yeah its getting pulled in via nokogiri
The issue really is the scanning tool, sees teh `tar.gz` extension, and wants to scan inside it. However since its not really a tar.gz file, it chokes and errors.  I'm going to see if I can reach with the folks on the scanning tool to better handle this.

I"m not sure how that file is used, but basically its not really a tar.gz file. Which is causing the issue we are seeing

**Comment by flavorjones** [comment]
The error you're seeing:

```
SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired)
```

looks like your machine may not have up-to-date CA certificates and so downloading the sqlite tarball is failing because SSL can't verify the cert.

But you don't need to run the full test suite. You can just run the unit tests with `rake test:unit` and it will skip the integration ("examples") tests.
