### ISSUE TITLE
[cmake] Support cross-compiling out of the box

### ISSUE THREAD

**Issue by stanhu** [flavorjones/mini_portile#128]
While working on https://github.com/mudge/re2/pull/67, I had to add a number of configuration options to make cross-compiling work properly.

For the standard `make`, mini_portile2 provides the `configure` script with the `--host` parameter, and the script figures out the target compilers to use. With CMake, we don't have that benefit so we need to set the C and C++ compilers ourselves.

I used a simple heuristic to find the target compilers:

1. For macOS, use `clang` and `clang++`. Otherwise use `gcc` and `gcc++`.
2. We search the PATH for `<host>-compiler`. Use that if we find it. Otherwise default to the base compilers.

To make CMake work with cross-compilation, a number of variables have to be set:

- CMAKE_SYSTEM_PROCESSOR
- CMAKE_SYSTEM_NAME
- CMAKE_C_COMPILER
- CMAKE_CXX_COMPILER

I was surprised that `CMAKE_SYSTEM_NAME` has to be set, or `cmake` won't try to cross-compile.

I think `mini_portile2` should provide these options by default.

**Comment by stanhu** [comment]
In order to build a C extension against a library, we may also want to add:

- CMAKE_POSITION_INDEPENDENT_CODE=ON

**Comment by flavorjones** [comment]
Ack. CMake is still "experimental" and you may be the first person to really try to use it for something. Will take a look, but prioritizing it behind some other work at the moment.
