### ISSUE TITLE
[Feature Request] Checksum mechanism needed

### ISSUE THREAD

**Issue by knu** [flavorjones/mini_portile#19]
If files are to be downloaded on user's site, size & checksum information for each download file should be included in a recipe and the files must be checked upon before being used.

What I have in mind is something like this:
```
recipe.distinfo = {
  "file or url" => {
    size: 1048576,
    sha256: '35c5803b469bd178a70c060ed83ba22e52fc9e4e754fefa53f783ce242098953',
  },
}
```

**Comment by flavorjones** [comment]
#54 has been merged, which implements this feature.
