### ISSUE TITLE
`git apply` fails depending on git configuration

### ISSUE THREAD

**Issue by mattbrictson** [flavorjones/mini_portile#32]
My `~/.gitconfig` had the setting `autocrlf = input`.

For some reason this caused mini_portile to fail to apply patches with `git apply`. I could not install nokogiri due to the problem. https://github.com/sparklemotion/nokogiri/issues/1095

The solution in this case was to change my git configuration by removing the autocrlf setting.

Is there a better way to address this issue?

**Comment by flavorjones** [comment]
For what it's worth, 0.7.0.rc1 will contain patches from #54 which will try to use `git apply`, then try to use `patch`, and then fail with a nice error message if neither is installed.
