### ISSUE TITLE
Assert correct behavior with more thorough tests.

### ISSUE THREAD

**Issue by balasankarc** [flavorjones/mini_portile#36]
Hi, I am trying to package mini_portile for Debian and it seems there are no tests written for it. Can you please write some tests so that we can package the gem?

**Comment by flavorjones** [comment]
I agree that we need better tests. I'll try to find time for this.

**Comment by balasankarc** [comment]
Thanks @flavorjones  . :)

**Comment by balasankarc** [comment]
@flavorjones Sorry if I sound pushy. Is there any update on tests?

**Comment by flavorjones** [comment]
Sorry, it's been very hard to find time to work on open source lately. I started a branch with a strategy to break out the code into unit-testable bits, but then I [lost my hard drive](https://twitter.com/flavorjones/status/588449381868818433) before pushing and just haven't had the energy to start over.

I'll find time to work on this while I'm on a plane next week.

**Comment by balasankarc** [comment]
@flavorjones  Thanks. :) 

PS : I may package this without tests as it is a dependency for some other gems that I am packaging. I guess we can cut a new release of mini_portile after you add tests. Hope that is fine with you. :)

**Comment by flavorjones** [comment]
Some testing has been added by @larskanis in #54, which is now on master.
