### ISSUE TITLE
mini_portile-0.6.1 identification error

### ISSUE THREAD

**Issue by taogone** [flavorjones/mini_portile#38]
I want to install redmine_dmsf but when run rake command to migrate database into "bitnami redmine stack 2.6.0-2 / windows 7 / ruby version 2.0.0", I have met mini_portile-0.6.1 is required but missing.

And "bundle check" command shows that gem is not installed and recommend to execute "bundle install" command. But "bundle install" command showed not any effect., just same situation.

Actually mini_portile-0.6.1 was installed successfully, can be found by "gem list mini" command.

Could you help me to install this gem?

**Comment by flavorjones** [comment]
Hi @taogone,

I apologize for not responding more quickly.

I don't fully understand your question. Can you explain a bit more about your problem? How would I reproduce this?

**Comment by flavorjones** [comment]
Hi @taogone,

Please let me know how I can help by re-opening this issue. In the meantime, I'll mark it closed.

Thank you!
