### ISSUE TITLE
Deprecate Ruby 1.8.7, 1.9.2 and 1.9.3

### ISSUE THREAD

**Issue by flavorjones** [flavorjones/mini_portile#45]
Presumably in the next major release.

**Comment by flavorjones** [comment]
Note that 1.8.7 is deprecated as of 0.7.0.rc1.

**Comment by flavorjones** [comment]
@larskanis Should we do this in mini_portile 2.0? At least, we should deprecate 1.8.7, I think.

**Comment by flavorjones** [comment]
Ah - 1.8.7 was removed in 2d470b9. 1.9.2 was removed in that same version, but restored in f1beaac because Nokogiri.

**Comment by larskanis** [comment]
I opt for keeping ruby-1.9.2 compatibility for now. Even if these versions are EOL, some gems might still want to support these old versions and want make use of mini_portile2.

**Comment by santhoshcd** [comment]
Hi flavorjones
                     Any update on @pitbulk ticket([300](https://github.com/onelogin/ruby-saml/issues/300))?
