### ISSUE TITLE
MiniPortile + configure in $PATH + non bourne /bin/sh + libxml2 = kaboom

### ISSUE THREAD

**Issue by glandium** [flavorjones/mini_portile#49]
Testcase:
- Ensure /bin/sh is not a bourne shell (/bin/dash, for example)
- Create a "configure" file with the following content:
```sh
#! /bin/sh
echo foo
exit 1
```
- Make it executable and place it in a directory in your $PATH, or add the directory containing it in your $PATH
- gem install nokogiri

The install fails with a message saying:
Running 'configure' for libxml2 2.9.2... ERROR, review '(...)/configure.log' to see what happened.
That configure.log contains "foo".

Why is there a configure in the PATH will you ask? Well, there are plenty of reasons you can end up with this (like building git yourself and adding the build directory in your PATH, not knowing you should add the bin-wrappers subdirectory instead).

The reason this is happening is that nokogiri's build script use MiniPortfile to compile libxml2, and MiniPortfile calls "sh configure" to run libxml2's configure. Presumably because Windows wouldn't know how to run "configure" alone. Now, this would be fine is libxml2's configure was not trying to reexecute itself with a bourne shell. To do so (this is an autoconf thing), it munges $0 and runs bash $the_result_of_the_munging.
The munging of $0 is done as follows:
- if it contains a / (like ./configure or $some_relative_path/configure would), keep $0 intact
- otherwise, scan $PATH to find a file named $0 (which is just "configure"). So it will expand "configure" to the path of that "configure" script in your $PATH and execute that.

The following would fix this:
```diff
diff --git a/lib/mini_portile/mini_portile.rb b/lib/mini_portile/mini_portile.rb
index 6913400..4598e21 100644
--- a/lib/mini_portile/mini_portile.rb
+++ b/lib/mini_portile/mini_portile.rb
@@ -63,7 +63,7 @@ class MiniPortile
     digest   = Digest::MD5.hexdigest(computed_options)
     File.open(md5_file, "w") { |f| f.write digest }
 
-    execute('configure', %Q(sh configure #{computed_options}))
+    execute('configure', %Q(sh ./configure #{computed_options}))
   end
 
   def compile
```

**Comment by flavorjones** [comment]
Merged #65 which should address this. Thank you!
