### ISSUE TITLE
Figure out why jruby-9.0.0.0 is failing tests

### ISSUE THREAD

**Issue by flavorjones** [flavorjones/mini_portile#57]
Currently I get this failure:

```
Running git apply with /home/flavorjones/code/oss/mini_portile/test/assets/patch 1.diff...
fatal: can't open patch '/home/flavorjones/code/oss/mini_portile/test/assets/patch': No such file or directory
```

the contents of the command are an array:

> ["git", "--work-tree=.", "apply", "/home/flavorjones/code/oss/mini_portile/test/assets/patch 1.diff"]

which indicates there's some kind of whitespace-handling that needs to be done. However, this test appears to pass on jruby-9.0.0.0:

```ruby
  def test_system_with_space_in_arg
    FileUtils.mkdir_p 'test_dir'
    File.open('test_dir/patch 1.diff', 'w') { |f| f.write "Hello, world." }
    system("ls test_dir")
    command = ["git", "--work-tree=.", "apply", File.expand_path("test_dir/patch 1.diff")]
    puts command.inspect
    assert(system(*command))
  ensure
    FileUtils.rm_rf 'test_dir'
  end
```

so I'm mystified as to what's going on.

**Comment by flavorjones** [comment]
Fixed.

**Comment by larskanis** [comment]
Looks like our test suite is working well by now. Thank you for fixing the platform issues!
