### ISSUE TITLE
Appveyor should run more versions of Ruby

### ISSUE THREAD

**Issue by flavorjones** [flavorjones/mini_portile#58]
I couldn't get this to work, for some reason I can't figure out. See these builds and commits for what didn't work:

* https://ci.appveyor.com/project/flavorjones/mini-portile/build/master-4 / https://github.com/flavorjones/mini_portile/commit/18e67adba674a072efb64c68868dca5a0952ae2c
* https://ci.appveyor.com/project/flavorjones/mini-portile/build/5 / https://github.com/flavorjones/mini_portile/commit/87407418dafa51494a2b164af48361ec2797b4cd
* https://ci.appveyor.com/project/flavorjones/mini-portile/build/6 / https://github.com/flavorjones/mini_portile/commit/82ad0a6d35a4edb45db832f20151696906409955

**Comment by larskanis** [comment]
@flavorjones Is this still valid? It looks like the last commit worked as expected: https://ci.appveyor.com/project/flavorjones/mini-portile/build/1.0.3

**Comment by flavorjones** [comment]
@larskanis You're right, no longer relevant.

**Comment by larskanis** [comment]
Great - everything wonderful green now!
