### ISSUE TITLE
Invoke configure directly, not by passing it to `sh`

### ISSUE THREAD

**Issue by ignisf** [flavorjones/mini_portile#64]
Hello,

Is there a reason I'm missing that explains why the `configure` script is getting invoked by passing it to `sh` instead of relying on the shebang?

**Comment by larskanis** [comment]
Yes - it is for Windows. Windows doesn't care about the shebang.

Also note that this issue is similar to #49 .

**Comment by ignisf** [comment]
It is somewhat similar, however invoking the configure script with `sh ./configure` does not take into account the shebang either.

My issue is with non-standard configure scripts that are written in bash for example.

**Comment by larskanis** [comment]
#65 should fix this.

**Comment by ignisf** [comment]
Thank you! :cat:
