### ISSUE TITLE
Use ruby tar for windows users

### ISSUE THREAD

**Issue by dsisnero** [flavorjones/mini_portile#75]
I tried using this in windows but there is no downloaded tar command.  The following gist shows how to use tar from ruby

https://gist.github.com/sinisterchipmunk/1335041

**Comment by larskanis** [comment]
It is possible to untar in ruby, but the advantage is minimal, because the
subsequent build process requires the Unix tool set nevertheless, in most
cases. Additionally we use the "patch" command and there is no ruby
substitution so far.
