### ISSUE TITLE
"RuntimeError: Digest::Base cannot be directly inherited in Ruby"

### ISSUE THREAD

**Issue by FireFart** [flavorjones/mini_portile#83]
This happend after updating all gems to the latest version:
https://hub.docker.com/r/wpscanteam/wpscan/builds/b5xh8jdtu33s3u9hcj8alec/

```
RuntimeError: Digest::Base cannot be directly inherited in Ruby
An error occurred while installing mini_portile2 (2.3.0), and Bundler cannot
continue.
Make sure that `gem install mini_portile2 -v '2.3.0'` succeeds before bundling.
```

This seems to be introduced in this commit: https://github.com/flavorjones/mini_portile/commit/c8d3442938c88ce7f2ebe6c3163d58c0fbdb4455#diff-03dcf58e9c53b59fc2bf7d60d421e400L7

**Comment by FireFart** [comment]
This is not fully reproducible. I suspect this to fail because of the `--jobs 8` parameter to run bundler in parallel.

**Comment by flavorjones** [comment]
@FireFart can you help me reproduce this?

**Comment by FireFart** [comment]
@flavorjones I expect this to be a race condition on some includes when running in parallel as it only happens from time to time so it might me hard to reproduce.

**Comment by flavorjones** [comment]
I'm going to go ahead and close this, unless you can help me reproduce. Will leave open for a few days before doing so.

**Comment by FireFart** [comment]
Sorry can't help to reproduce since it's a random error
