### ISSUE TITLE
Unable to download files when Content-Encoding is chunked

### ISSUE THREAD

**Issue by eagletmt** [flavorjones/mini_portile#85]
`MiniPortile#download_file_http` relies on the Content-Length header, but it isn't sent when Content-Encoding is chunked. In this case, `content_length_proc` is called with nil.
https://github.com/flavorjones/mini_portile/blob/v2.3.0/lib/mini_portile2/mini_portile.rb#L454-L460
Although mini_portile requests with `Accept-Encoding: identity`, some servers (e.g., GitHub) respond with `Content-Encoding: chunked`

**Comment by flavorjones** [comment]
Closing the loop: this was addressed via #86 in v2.4.0.
